### ISSUE TITLE
Redirect error to index

### ISSUE THREAD

**Issue by AaaCabbage** [bitovi/github-actions-deploy-static-site-to-aws#17]
I have deployed a front-end single-page application to S3. Since the SPA needs to manage all routes on the front end, any errors should be redirected to index. However, without enabling the CDN, I couldn't find any configuration option for error_document. Is it possible to add an option for configuring the error document or a place to configure redirect_all_requests_to?

**Comment by AaaCabbage** [comment]
Alternatively, another approach could be that I already have an AWS bucket configured, and this GitHub script only needs to update the new static files without overwriting the manually modified err document configuration every time.

**Comment by LeoDiazL** [comment]
Hi @AaaCabbage ! Thanks for opening an issue. 

There are different possible solutions. 
One would be to be taken care by the code itself (index.html)
The other one is with CDN or a lambda function. 

This action covers only the CDN option, at least for now. If you could propose any other solution, and can submit a draft PR, we will check it and let you know if we can add it, if you can only propose the idea itself, we'll have to investigate it and check if it's feasible. Either way, we will welcome any suggestion. 

Thanks again!

Leo

**Comment by AaaCabbage** [comment]
> Hi @AaaCabbage ! Thanks for opening an issue.
> 
> There are different possible solutions. One would be to be taken care by the code itself (index.html) The other one is with CDN or a lambda function.
> 
> This action covers only the CDN option, at least for now. If you could propose any other solution, and can submit a draft PR, we will check it and let you know if we can add it, if you can only propose the idea itself, we'll have to investigate it and check if it's feasible. Either way, we will welcome any suggestion.
> 
> Thanks again!
> 
> Leo

**Comment by AaaCabbage** [comment]
Hi @Leo,

Thank you so much for your prompt and detailed response!

I’m not very familiar with the Terraform framework, but I’ve opened a new PR where I’ve attempted to add the aws_site_error_document configuration based on the Terraform documentation. I would really appreciate it if you could take a look at the code and provide any feedback or suggestions if there are issues.

Thanks again for your help!

Best regards,
AaaCabbage

**Comment by LeoDiazL** [comment]
Hi @AaaCabbage ! Thanks for your suggestion! 
I wasn't aware such option existed. 

Your PR looks neat. Have you tested it yourself? Let me know if you need directions on how to test it. 

As soon as we have some time, we'll conduct some tests and merge it. Thanks again for your input!

**Comment by AaaCabbage** [comment]
Hi @Leo,

Thank you so much for the kind words and for recognizing my work on the PR!

I’ve already tested the changes on my own project. To do so, I published the modified action to the GitHub Action Marketplace and then applied it in my project. After deploying, I checked the S3 bucket's website configuration and confirmed that the error document was correctly set as expected.

However, I’d appreciate it if you could verify that my testing approach aligns with your project's standards. If there’s anything I missed or if further adjustments are needed, I’m happy to help out.

Thanks again for your support!

**Comment by LeoDiazL** [comment]
Hi @AaaCabbage, we are always happy to receive contributions. 

The code looks good, tested it and does what it should. The only thing is that if we don't have an error.html document, then it will map it to that one as default, making it show another message saying that the error.html file is missing. 

So, we would need that error doc block to be dynamic and create it only if there's an error file present. 
If you manage to make that happen, awesome! If not, I'll try to make some time this week, merge this and add that feature. 

Thanks again for your contribution!

**Comment by AaaCabbage** [comment]
Hi @LeoDiazL
Thank you for pointing that out!

I hadn’t noticed the issue with the missing error.html leading to the extra message. One thing that may have contributed to my confusion is the S3 web UI, where the error document field has a placeholder set to error.html, which led me to believe that this was the default behavior if nothing was configured.

I’ve now updated the code to set the error document to an empty string by default. I believe this aligns better with S3’s default behavior and should prevent any unnecessary error messages from appearing.

Thanks again for your feedback, and please let me know if there’s anything else I should adjust!

**Comment by LeoDiazL** [comment]
Hi @AaaCabbage ! 

Added a comment in the [PR](https://github.com/bitovi/github-actions-deploy-static-site-to-aws/pull/18), I could test it again once that's merged, and if it works, then we'll :shipit: 

Thanks again!

**Comment by LeoDiazL** [comment]
Thanks for your suggestion @AaaCabbage ! it's now live in [0.2.3](https://github.com/bitovi/github-actions-deploy-static-site-to-aws/releases/tag/v0.2.3)!
