### ISSUE TITLE
Only AWS or every S3 compatible Bucket?

### ISSUE THREAD

**Issue by DarioSoller** [bitovi/github-actions-deploy-static-site-to-aws#9]
Does this GH action really only work with AWS S3 or with every S3 compatible storage. So for example with Cloudflare's R2 bucket in my case? The reason why I am asking is, that my organization only allows the usage of Github actions in our Github enterprise by verified authors of the Github.com marketplace. Unfortunately there is no rclone Github action with a verified author yet.

Thanks for clarification.

**Comment by LeoDiazL** [comment]
Hi @DarioSoller ! Thanks for opening up the issue!

Yes, at the moment, only AWS is supported. 

In fact, we use multiple things from AWS in this action, bucket to store Terraform state, load balancer, DNS, CDN, etc. 
Is it only the bucket what you need to host on Cloudflare? If so, please adjust the issue title to reflect that, and when we have the bandwidth, we'll work on it. 

If it's more than that, we are happy and open to discuss any need. You can reach us through [Discord](https://discord.gg/zAHn4JBVcX), or set up a [free consultation with us](https://www.bitovi.com/services/devops-consulting).

I can also suggest using our [React to GH Pages action](https://github.com/bitovi/github-actions-react-to-github-pages).
We have another one for Storybook too. 

Once again, thanks for opening up an issue with us!

Leo.

**Comment by DarioSoller** [comment]
My hope has been that it maybe uses [rclone](https://rclone.org/) under the hood. If that would have been the case, it automatically would have meant that any S3 compatible cloud storage is supported. Anyhow, thanks for your quick response to my issue. Unfortunately I think this than is not the right GH action in my case.
